// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monitor_covid19.Models;

namespace monitor_covid19.Migrations
{
    [DbContext(typeof(CovidContext))]
    [Migration("20200515200754_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("monitor_covid19.Models.InfeccaoModel", b =>
                {
                    b.Property<int>("InfeccaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasosConfirmados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mortes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recuperados")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfeccaoId");

                    b.ToTable("Infeccoes");
                });

            modelBuilder.Entity("monitor_covid19.Models.PaisModel", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
