// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monitor_covid19.Models;

namespace monitor_covid19.Migrations
{
    [DbContext(typeof(CovidContext))]
    partial class CovidContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("monitor_covid19.Models.InfeccaoModel", b =>
                {
                    b.Property<int>("InfeccaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasosConfirmados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mortes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaisRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recuperados")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfeccaoId");

                    b.HasIndex("PaisRef")
                        .IsUnique();

                    b.ToTable("Infeccoes");
                });

            modelBuilder.Entity("monitor_covid19.Models.PaisModel", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("monitor_covid19.Models.InfeccaoModel", b =>
                {
                    b.HasOne("monitor_covid19.Models.PaisModel", "Pais")
                        .WithOne("Infeccao")
                        .HasForeignKey("monitor_covid19.Models.InfeccaoModel", "PaisRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
